# server
server:
  port: 80

spring:
# datasource
  profiles:
    active: dev

# thymeleaf
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    mode: HTML
    encoding: utf-8
    content-type: text/html

# pagehelper(https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/HowToUse.md)
  pagehelper:
    offset-as-page-num: true
    helper-dialect: mysql
    row-bounds-with-count: true
    reasonable: true

# 多配置文件
---
spring:
  profiles: dev
server:
  port: 8080

---
spring:
  profiles: prd
server:
  port: 80